"""Vendored INIM PrimeX API client — self-contained, no external package needed."""

from .api import (
    InimApiError,
    InimConnectionError,
    InimError,
    InimPrimeClient,
)
from .const import (
    API_PATH,
    ApiStatus,
    AreaMode,
    AreaState,
    ArmMode,
    Command,
    ZoneState,
)
from .local6004 import (
    Local6004Client,
    Local6004Config,
    Local6004Error,
    SceneDef,
    decode_event_log,
    decode_scene,
    scene_is_active,
)
from .models import (
    FAULT_FLAG_KEYS,
    ApiStats,
    Area,
    Fault,
    IpAcl,
    MacAcl,
    OpenZone,
    Output,
    Scenario,
    Timer,
    Version,
    Zone,
    parse_decimal,
)

__all__ = [
    "API_PATH",
    "ApiStatus",
    "ArmMode",
    "AreaMode",
    "AreaState",
    "Command",
    "ZoneState",
    "ApiStats",
    "Area",
    "Fault",
    "FAULT_FLAG_KEYS",
    "IpAcl",
    "MacAcl",
    "OpenZone",
    "Output",
    "parse_decimal",
    "Scenario",
    "Timer",
    "Version",
    "Zone",
    "InimApiError",
    "InimConnectionError",
    "InimError",
    "InimPrimeClient",
    "Local6004Client",
    "Local6004Config",
    "Local6004Error",
    "SceneDef",
    "decode_event_log",
    "decode_scene",
    "scene_is_active",
]
